### ISSUE TITLE
의뢰에 의한 지출 내역 뿐만이 아닌 추가적인 수입/지출을 유연하게 받을 수 있어야함

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#113]
저 부분에서 해결 바라고,
![image](https://user-images.githubusercontent.com/15524302/81028097-0a3cb280-8ebb-11ea-8114-e8edd141f2e9.png)

이 아래 부분과 호환되도록 작성하면 좋을 것 같음
![image](https://user-images.githubusercontent.com/15524302/81028115-19236500-8ebb-11ea-91c6-db8a477ce704.png)

내용 대신 type이 들어갔으나, type이 string인데 이 부분에다가 그냥 작성하면 되는건가요?

**Comment by cg140428** [comment]
풀리퀘할때 text로 바꾸라의견줘서 변경했는데
```
STATE_CHOICES = (
	('RED', 'before_permission'),
        ('RUN', 'running'),
        ('END', 'end'),
)
```
type 필드를 이런식으로 하는건 어떠세유

**Comment by cg140428** [comment]
해당 사용자에 대한 보유 포인트도 수입/지출에 따라 변경해야겠다.
