### ISSUE TITLE
API에서 가입에 필요한 모든 회원정보를 받지 않음

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#116]
![image](https://user-images.githubusercontent.com/15524302/81030610-648e4100-8ec4-11ea-8c5c-8b5157a743e0.png)

아래 API는 위 회원가입을 감당하기에 없는 입력값이 존재함

fullname(실명)
birthday(생년월일)

추가바랍니다.

![image](https://user-images.githubusercontent.com/15524302/81030597-5b04d900-8ec4-11ea-8137-b535da515a8a.png)

**Comment by cg140428** [comment]
User.py
```
fullname = graphene.String()
birthday = graphene.String()
```
