### ISSUE TITLE
[FE]파일 업로드 컴포넌트

### ISSUE THREAD

**Issue by jjolbo** [kookmin-sw/capstone-2020-6#123]
- 파일 업로드 컴포넌트 생성

**Comment by jjolbo** [comment]
@jtjisgod  @YoonYeoHwan  파일 업로드 버튼 부분 css 수정해주세요.. 아니면 하는 방법 좀 알려주세요. 자꾸 안 먹네요

**Comment by YoonYeoHwan** [comment]
저는 잘 모르겠음,, @jtjisgod 부탁해여
