### ISSUE TITLE
[BE] Implement createRequest Function

### ISSUE THREAD

**Issue by cg140428** [kookmin-sw/capstone-2020-6#14]
createRequest 함수는 의뢰자의 주제 요청(관리자의 승인 받는 과정 이전)을 수행한다.

질문 사항
- 인스턴스 생성과 동시에 정의 되지 않는 total_point (총 가격) attribute에 대한 부분 
- table의 fk에 대한 create 과정

**Comment by jtjisgod** [comment]
Resolved
1ef7df4e1b32741d46ff7f086adc2ba49774f33b
