### ISSUE TITLE
create코드 효율적으로 변경

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#142]
부탁드립니다.
조건문의 흐름에 따라 효율적인 처리가 가능하도록 해주시고, 중복된 코드가 여러개 존재하는 경우 디버깅에 혼란이 오니 합쳐주시길바랍니다.
![image](https://user-images.githubusercontent.com/15524302/81492604-17e7a300-92d4-11ea-9162-de6090b1c045.png)

**Comment by cg140428** [comment]
객체생성 코드 부분 하나로 줄였습당
