### ISSUE TITLE
/mypage/projects 에서 주제 선택하면 해당 주제 보여주는 페이지로 이동시켜주세요.

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#145]
![image](https://user-images.githubusercontent.com/15524302/81493259-eeca1100-92d9-11ea-813b-36daea46e042.png)

해줘요.

**Comment by jjolbo** [comment]
저 테이블이 의뢰자 페이지 기준으로 만든것이라 일단 의뢰자의 경우, 해당 라벨링 주제 업데이트 페이지로 이동하게 바꾸었습니다.
