### ISSUE TITLE
/mypage/projects 더미 데이터 없애주시고, 로딩 화면 구현해주세요.

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#146]
![image](https://user-images.githubusercontent.com/15524302/81493294-25a02700-92da-11ea-8e1e-735a6af6eed7.png)

**Comment by YoonYeoHwan** [comment]
로딩 화면은 어떤 것을 원하는지 구체적인 설명 부탁드립니다.

**Comment by jtjisgod** [comment]
배경 검정색으로 만들 고 가운대에 
![image](https://user-images.githubusercontent.com/15524302/82020415-fddb0580-96c3-11ea-950c-86b1301381c6.png)

**Comment by YoonYeoHwan** [comment]
![image](https://user-images.githubusercontent.com/28583545/82021599-12200200-96c6-11ea-9cd7-2d528185e971.png)

로딩을 어느 타이밍에 넣고 싶은지 캐치가 안돼서, 일단 Component 로 디자인만 했는데, 이거 디자인은 괜찮습니까?

**Comment by YoonYeoHwan** [comment]
semantic ui 에서 Dimmer 랑 Loader 불러와서 사용했습니당
