### ISSUE TITLE
의뢰 열람을 위한 개별 id를 받아 1개만 보여주는 기능이 구현되지 않았음

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#153]
해주세요 @cg140428 
![image](https://user-images.githubusercontent.com/15524302/81494435-e5de3d00-92e3-11ea-998f-6f81e8d2019e.png)

**Comment by cg140428** [comment]
되는 코드로 했어요,,, object.filter썼는데 머라하지 마세요!
