### ISSUE TITLE
/labeling/:postId 부분 추가 요청

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#173]
![image](https://user-images.githubusercontent.com/15524302/82114271-b07b9880-9796-11ea-92c4-30ea6567a8fe.png)

- [x] 기간 부분 수정 바람
- [x] 연습하고 시작하기 누르면 왜 이동안함?
- [x] 프로그래스바 작동 안됨
- [x] "보상을 지급하고 조기종료" 버튼 만들기

**Comment by YoonYeoHwan** [comment]
프로그래스바 해결

**Comment by YoonYeoHwan** [comment]
기간은 일단 수정 해두었는데, 서버 연결이 이상한지 데이터가 제대로 안불러와져서 확인을 못했음.
아마 연결되면 제대로 불러올 것 같긴 한데, 연결 되고 다시 한번 확인 하겠음.

**Comment by YoonYeoHwan** [comment]
보상을 지급하고 조기 종료는 저 페이지에 만들어야하나?
나는 레이블링 진행중인 페이지에 만들어야한다고 생각을 했는데?

**Comment by YoonYeoHwan** [comment]
연습하고 시작하기 누르면 이동하지 않는 문제는 확인해보니 버튼 누르면 `PageLabeling.tsx` 파일 line 28에 `handleLink` 함수에서 url 처리해주는데, 이거 역시 서버 연동 문제 해결되면 바로 수정해주겠음.

**Comment by YoonYeoHwan** [comment]
연습하고 시작하기 해결 중인데, DB 에 라벨링 유형이 어떻게 저장되어 있는지 몰라서 아래 사진 보고 확인 부탁해요.

![image](https://user-images.githubusercontent.com/28583545/82126541-68856180-97e8-11ea-8003-8b6d5d31b408.png)

- [TEXT] 객관식
- [TEXT] 단답식
- [IMAGE] 선택형
- [IMAGE] 캡쳐형

내 느낌대로 일단 코드에는 해놓았는데 코멘트 한번 확인 부탁.

**Comment by jtjisgod** [comment]
1. 조기종료는 그냥 버튼 하나로 끝내자. 그리고 결과를 볼 수 있는 페이지 확인 할 필요가 있어보임

2. 연습하고 시작하기 해결 중인데, DB 에 라벨링 유형이 어떻게 저장되어 있는지 몰라서 아래 사진 보고 확인 부탁해요
-> 이건 category { type, name, idx } 로 graphql에서 받아온다음에 idx로 해야하는데 내가 안했어, 그 부분은 내가 할게 그냥 넘기슈
