### ISSUE TITLE
메인페이지 이미지 없는 경우 NoImage 뛰우고 프로그래스바등 잘 나오도록 해주세요

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#180]
![image](https://user-images.githubusercontent.com/15524302/82119589-c26f3280-97ba-11ea-8336-ab7077b90761.png)

**Comment by YoonYeoHwan** [comment]
이미지 없는 경우는 문제 해결
프로그래스는 연동 문제 해결후 다시 확인하겠음.

**Comment by YoonYeoHwan** [comment]
Progress Bar 확인해보니 애초에 react semantic ui 에서 제공할 때 0% 일 때도 칸이 조금 채워져있음.
태진이가 캡쳐해준 것들도 정상이란 이야기. semantic ui 라이브러리 가져다 쓸거면 
![image](https://user-images.githubusercontent.com/28583545/82126193-fd3a9000-97e5-11ea-9dfc-4716e7cf9334.png)
이런식으로 진행률 퍼센트를 띄워주는 방법이 있을 것 같음.
다른 의견 주세요. @jtjisgod @jjolbo

**Comment by jtjisgod** [comment]
좋음
