### ISSUE TITLE
[FE] Fix search error in PageViewAllProjects.tsx

### ISSUE THREAD

**Issue by YoonYeoHwan** [kookmin-sw/capstone-2020-6#183]
- 검색할 때 검색 버튼을 두번 눌러야 검색이 되서 이 문제 수정해야함.

**Comment by YoonYeoHwan** [comment]
비동기로 문제 해결할 예정..
근데 다른 버그가 터져서 딜레이가 계속 된다..

**Comment by YoonYeoHwan** [comment]
- 메인 페이지에서 더보기 들어가면 데이터 로딩보다 화면 랜더링이 빨라서 처음에 빈 리스트가 나오는 경우가 있음
- 더보기 페이지에서 검색을 했을 때도 검색 버튼을 두번 눌러야 검색 내용이 랜더링 되는 문제가 있음
`ProjectListStore.ts` 내의 함수 설명 간단히
- `getProjects` : 진행중인, 완료된 전체 프로젝트 가져오기
- `getProjectsWithLimit` : 진행중인, 완료된 프로젝트 중 몇개만 가져오기
- `searchProjects` : 진행중인, 완료된 프로젝트 검색하기(완료된 프로젝트 검색부분 비어있음)

**Comment by jtjisgod** [comment]
1d4d0330d97fca1b50f331a5ce77d2ccffd404c9
