### ISSUE TITLE
"참가자" 입장에서 "나의 프로젝트" 들어가면 입장한 프로젝트 안보임

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#219]
http://localhost:3000/mypage/projects

**Comment by cg140428** [comment]
나의 프로젝트를 보려면 getLabelerTakenProject 함수 사용하셔야합니당

**Comment by cg140428** [comment]
@jtjisgod 
getMyProject 함수로 의뢰자/참여자 구분없이 사용가능하게 만들었음
의뢰자: 자신이 등록한 프로젝트 나열
참여자: 자신이 신청한 프로젝트 나열
