### ISSUE TITLE
[FE] Text Labeling Button Overlapping bug fix

### ISSUE THREAD

**Issue by YoonYeoHwan** [kookmin-sw/capstone-2020-6#37]
store 에서 Button 을 불러오는 과정에서 버튼이 겹치는 문제가 발생.
버튼 겹침을 해결해서 1줄에 2개씩 나오도록 수정해야함.
페이지 : PageLabelingTextButton.tsx
컴포넌트 : LabelingTextButton.tsx

**Comment by jtjisgod** [comment]
c124c1ad1eb790d258baedc11973ecbe811a6517
goruf
