### ISSUE TITLE
[FE] 라우팅 관련 처리가 왜 중복되나요

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#56]
![image](https://user-images.githubusercontent.com/15524302/79598481-fbb27500-811e-11ea-821c-1382f4756a5b.png)

설명해주세요
@YoonYeoHwan

**Comment by YoonYeoHwan** [comment]
Rebase 하면서 중복으로 들어간 것 같습니다.
수정에서 push 하겠습니다.
