### ISSUE TITLE
[FE] 정적인 페이지, 정적인 데이터를 스토어에 사용하면 안됩니다.

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#57]
상태관리 잘하셔야합니다.
전부다 스토어에 넣으면 느려집니다.. @jjolbo 
https://github.com/kookmin-sw/capstone-2020-6/blob/699265737d73db2cd01f2c798edc13d431fd7637/web-frontend/src/pages/PageAbout.tsx#L36

**Comment by jtjisgod** [comment]
이건 그냥 하드코딩 하셔도 되는 부분입니다.

**Comment by YoonYeoHwan** [comment]
About page 수정된거 같은데 그럼 AboutStore.ts 파일 삭제해도 되나요?

**Comment by jjolbo** [comment]
네
