### ISSUE TITLE
[FE] `/mypage/projects` 부분 디자인 제안

### ISSUE THREAD

**Issue by jtjisgod** [kookmin-sw/capstone-2020-6#68]
`/mypage/projects`은 서브페이지처럼 보이게 대문 사진 없애고 리스트 형식으로 가는거 어떠세요
@jjolbo @YoonYeoHwan

**Comment by YoonYeoHwan** [comment]
그러면 썸네일 안보이게하고 그냥 프로젝트 이름만 리스트처러 보이도록??

**Comment by jtjisgod** [comment]
일단 메인과 다르게

**Comment by jjolbo** [comment]
메인이랑 다르게 다시 생각해볼게요~
